# Config file for go-test-coverage github action.

profile: cover.out
local-prefix: github.com/FIAP-SOAT-G20/tc4-customer-service
threshold:
  total: 80
exclude:
  paths:
    - docs/*
    - internal/infrastructure/pkg/*
    - internal/core/domain/value_object/*
    - internal/infrastructure/aws/lambda/*
    - cmd/worker/consumer/main.go
    - health_check_handler.go
    - main.go
    - ^.*_mock\.go$
    - ^.*_request\.go$
    - ^.*_response\.go$
    - ^.*_gateway\.go$
    - ^.*_datasource\.go$
    - ^.*_presenter\.go$
    - ^.*middleware.*
    - ^.*config.*
    - ^.*route.*
    - ^.*util.*
    - ^.*database.*
    - ^.*server.*
    - ^.*logger.*
    - ^.*httpclient.*
    - ^.*service.*
    - ^.*_entity\.go$
    - ^.*errors\.go$
    - ^.*_dto\.go$
    - ^.*_model\.go$
    - ^.*pagination\.go$
    - test/*
    - internal/infrastructure/datasource/model/*