services:
  db:
    image: mongo:8.0-noble
    container_name: db.10soat-g22.dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=fastfood_10soat_g22_tc4
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - fastfood_10soat_g22_tc4_network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  dbadmin:
    image: mongo-express:1.0.2-20
    container_name: dbadmin.10soat-g22.dev
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@db:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - fastfood_10soat_g22_tc4_network
    restart: unless-stopped

volumes:
  db_data:
    driver: local

networks:
  fastfood_10soat_g22_tc4_network:
    driver: bridge
