services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local.10soat-g22.dev
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory" ]
    ports:
      - "8000:8000"
    networks:
      - fastfood_10soat_g22_tc4_network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/ || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin.10soat-g22.dev
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb-local
    networks:
      - fastfood_10soat_g22_tc4_network
    restart: unless-stopped

networks:
  fastfood_10soat_g22_tc4_network:
    driver: bridge
