name: ci/integration-tests

on:
  workflow_run:
    workflows: [ "ci/unit-tests" ]
    types: [ completed ]
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    name: integration tests
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      github.event_name == 'pull_request'
    
    steps:
      - uses: actions/checkout@v4

      - name: 🚀 Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: 🗄️ Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.1
        with:
          port: 8000
          cors: '*'
          sharedDb: true
          version: '2.5.2'

      - name: 🛠️ Create .env
        run: cp .env.example .env

      - name: ✅ Run integration tests
        env:
          ENVIRONMENT: test
          DYNAMODB_TABLE_NAME: tc4-customer-service-test-customers
          DYNAMODB_REGION: us-east-1
          TEST_DYNAMODB_ENDPOINT: http://localhost:8000
        run: make integration-test