name: ci/integration-tests

on:
  workflow_run:
    workflows: [ "ci/unit-tests", "ci/linter", "ci/security-checks" ]
    types: [ completed ]
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    name: integration tests
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      github.event_name == 'pull_request'
    
    services:
      mongodb:
        image: mongo:8.0
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
          MONGO_INITDB_DATABASE: ${{ secrets.MONGO_INITDB_DATABASE }}
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })' --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4

      - name: 🚀 Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install MongoDB Shell
        run: |
          wget -qO- https://www.mongodb.org/static/pgp/server-8.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/8.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Wait for MongoDB to be ready
        run: |
          echo "Waiting for MongoDB to be ready..."
          timeout 60s bash -c 'until mongosh --quiet --eval "db.runCommand({ ping: 1 })" mongodb://${{ secrets.MONGO_INITDB_ROOT_USERNAME }}:${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}@localhost:27017/${{ secrets.MONGO_INITDB_DATABASE }}?authSource=admin; do sleep 2; done'
          echo "MongoDB is ready!"

      - name: 🛠️ Create .env
        run: cp .env.example .env

      - name: ✅ Run integration tests
        env:
          ENVIRONMENT: test
          MONGODB_URI: mongodb://${{ secrets.MONGO_INITDB_ROOT_USERNAME }}:${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}@localhost:27017/${{ secrets.MONGO_INITDB_DATABASE }}?authSource=admin
        run: make integration-test